name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      description:
        description: 'Ambiente de deploy'
        required: True
        default: 'dev'

env:
  environment: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

