name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      